server:
  port: 8090

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/it52
          jwk-set-uri: http://keycloak:8080/realms/it52/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: it52-client
            client-secret: vHgP94O0lsGldQHfcHreP02y4X0PsRKQ
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/it52
            authorization-uri: http://keycloak:8080/realms/it52/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/it52/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/it52/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/it52/protocol/openid-connect/certs
            user-name-attribute: preferred_username
jwt:
  auth:
    converter:
      resource-id: it52-client
      principal-attribute: preferred_username